project_name: some_project_name
project_description: Some description
gcp_dev_project_id: 123456789
gcp_prod_project_id: 987654321
pipeline_owner: Some Pipeline Owner
schedule_interval: 0 7 * * 1-3
use_ingestion: False